name: q_architecture
description: >
  A set of reusable classes that should speed up your development time  and
  reduce unnecessary boilerplate code.
version: 2.1.3
repository: https://github.com/Q-Agency/Q-Architecture
issue_tracker: https://github.com/Q-Agency/Q-Architecture/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  either_dart: ^1.0.0
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  get_it: ^9.2.1
  meta: ^1.17.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
